### ISSUE TITLE
http://oldpaper.g0v.ronny.tw/ doesn't work?

### ISSUE THREAD

**Issue by leo424y** [ronnywang/lagnews#2]
Please bring it back~

**Comment by leo424y** [comment]
不過api看起來是work的，應是view跑掉

**Comment by ronnywang** [comment]
已經修好囉， commit 在 70632316fc8ad2abe013f232eb210b4f11eaa1af
本來是從中央社 FB 粉絲專頁抓每天的「小編報頭條」
不過因為 FB Access key 過期，加上小編不定期會改寫法，所以很長一段時間無資料
所以後來改成直接從中央社新聞直接抓頭條
現在就把過去的資料也補齊了

**Comment by leo424y** [comment]
@ronnywang ，感謝你勞心勞力修正！
